### ISSUE TITLE
insecure direct object reference vulnerability

### ISSUE THREAD

**Issue by butchewing** [radgeek/feedwordpress#148]
I'm getting a warning in Solid Security Pro of an insecure direct object reference vulnerability.

> WordPress FeedWordPress plugin <= 2022.0222 - Insecure Direct Object Referece vulnerability

Is this a known vulnerability?
Is there a patch on the way for this?

**Comment by radgeek** [comment]
Hi there, thanks for checking in about this. I am aware of the issue.

I have a relatively simple fix for the concern raised, which I hope to be able to push (both to Github and to the WordPress plugins SVN repository) within the next day or two.

**Comment by radgeek** [comment]
I apologize that it's taken me all this time to follow up on this. It took a minute due to a combination of some travel and the review process involved with getting this fix made available in the WordPress Plugins Repository. But the issue should be resolved in the most recent release of FeedWordPress.  The suggested path for addressing the vulnerability is to upgrade to the current version of the plugin. (2024.0428), which is available either with a pull from this here repository, or from the (now-reopened) WordPress Plugin Repository copy.
