### ISSUE TITLE
SimplePie ReflectionClass Error when adding feed

### ISSUE THREAD

**Issue by travisjtodd** [radgeek/feedwordpress#15]
I'm getting this error when trying to add a feed.

```
Fatal error: Class 'ReflectionClass' not found in /var/www/localhost/htdocs/wp-includes/SimplePie/Registry.php on line 183
```

**Comment by tristanleboss** [comment]
Old issue but if you come here because you have this issue, you just need PHP 5.0. PHP < 5.0 doesn't have this functionality.

**Comment by radgeek** [comment]
@tristanleboss : Yep, thanks for pointing this out.

I'm going to go ahead and close this issue, because it is a SimplePie issue, not a FeedWordPress issue per se. FeedWordPress depends on the SimplePie module that ships with WordPress, but the version of SimplePie and the dependencies that come with that are not under my control. Recent versions of WordPress require PHP 5.2.4 or greater and recommend PHP 5.4 (<https://wordpress.org/about/requirements/>); although they may mostly run on lower versions, there's no guarantee of that. Unfortunately, you'll just have to do what you can to get your web hosting provider to upgrade their PHP installation to a more modern version.

HTH.

-C
