### ISSUE TITLE
Wordpress 6.7 PHP Fatal Error - Uncaught TypeError

### ISSUE THREAD

**Issue by danwie** [radgeek/feedwordpress#152]
**Updating (WEBSITE) (FEED) …There has been a critical error on this website. Please check your site admin email inbox for instructions….**

`2024/11/14 08:00:03 [error] 42175#42175: *33917035 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SimplePie\Cache\BaseDataCache::__construct() must implement i
nterface SimplePie\Cache\Base, instance of FeedWordPie_Cache given, called in /www/p/public_html/wp-includes/SimplePie/src/SimplePie.php on line 3219 and defined in /www/p/public_html/wp-includes/S
implePie/src/Cache/BaseDataCache.php:63
Stack trace:
#0 /www/p/public_html/wp-includes/SimplePie/src/SimplePie.php(3219): SimplePie\Cache\BaseDataCache->__construct(Object(FeedWordPie_Cache))
#1 /www/p/public_html/wp-includes/SimplePie/src/SimplePie.php(1585): SimplePie\SimplePie->get_cache('https://www.pro...')
#2 /www/p/public_html/wp-content/plugins/feedwordpress/feedwordpress.php(2020): SimplePie\SimplePie->init()
#3 /www/p/public_html/wp-content/plugins/feedwordpress/syndicatedlink.class.php(100): FeedWordPress::fetch(Object(SyndicatedLink), Array)
#4 /www/p/public_html/wp-content/plugins/feedwordpress/syndicatedlink.class.php(" while reading response header from upstream, client: 172.71.111.90, server: www.p.se, request: "GET /?update_feedwo
rdpress=1 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-p.sock:", host: "www.p.se"`

**Comment by lentemoore** [comment]
Had the same issue. Downgrade to WP 6.6.2. temporarily fixed it.

**Comment by radgeek** [comment]
Hey all, this is due to a new version of SimplePie included in the WordPress 6.7 update, which introduces some type declarations that are no doubt a good idea in the long run, but unfortunately break backward compatibility for classes extending `SimplePie\Cache` (formerly `SimplePie_Cache`), which includes the class FeedWordPress uses to cache responses from HTTP requests for subscribed feeds.

I did some initial testing and have pushed a small patch which I believe should cleanly fix this issue. Feel free to pull the latest from Github and let me know if it solves the issue for you. If so, great; if not, let me know what you are seeing in your error logs or in a screenshot.

If everything looks good with further testing of this patch, I anticipate that it should be packaged up into a point release and pushed out to both Github and the WordPress Plugins SVN repository over the weekend.

**Comment by talgalili** [comment]
You rock!

**Comment by saschafoerster** [comment]
Works for me. :) Thanks!

**Comment by tmuka** [comment]
the patched files fixed the fatal errors for me too. I'll appreciate an updated Version: # when you're ready.

Thanks!

**Comment by poVoq** [comment]
Works great, thanks a lot!
