### ISSUE TITLE
Feature Request: Automatic Deletion of Read more link

### ISSUE THREAD

**Issue by alex42ka** [radgeek/feedwordpress#48]
Hi,

today I've experienced a problem with FeedWordpress: I'm fetching a blog feed (entire article). On my blog the entire article is shown. But when searching content only excerpts are presented. After the excerpt two Read more links are shown. One of the feed and one of the blog.
I've already found a description how to crop the original link:

http://www.thatstevensguy.com/programming/how-to-improve-feedwordpress/

the mentioned code has to be included in the functions.php

Would be great to have the automatic deletion of the read more link integrated in Feedwordpress!

**Comment by radgeek** [comment]
Hi @alex42ka :

Thanks for writing, and for passing along this link. I understand why it would be desirable to strip out these links in your specific use-case. However, I don't have any plans to integrate this kind of filtering into the core FeedWordPress code.

In general, my view is that content filtering is best left up to the user through the programmable filtering hooks that FeedWordPress makes available. The article you posted here does a reasonably good job of explaining how to use them. My reasons for not putting filtering like this into the core FeedWordPress code is, briefly, that in my experience, different users (or even the same user, when looking at two different source feeds) tend to have very widely different needs in terms of how much or how little filtering they need done, and in terms of what they do or don't want stripped out of the content of syndicated posts. It would be extremely difficult to anticipate needs for filtering data out without a fair amount of knowledge about the particular, local circumstances for an individual user's website and for the specific feeds that they are trying to syndicate. Doing this correctly is easy to do in any individual instance, because you can pretty narrowly customize your filtering code to your own use-case, but very difficult to do in any general way without that kind of customization, and doing it incorrectly is sure to lead to bad, or even disastrous results for the user. (If something's not *supposed* to be stripped out, then incorrectly stripping it out inflicts a pretty high cost for the user.) 

So the programmable hooks are there for people to do the filtering they need, and leave out any filtering they don't need. If you have any question about how best to implement this custom filtering feel free to ask.

-C
