### ISSUE TITLE
Post needs wp_slash before wp_insert_post

### ISSUE THREAD

**Issue by himselfv** [radgeek/feedwordpress#49]
When new post is being syndicated in syndicatedpost.class.php, there's this code:

			// O.K., is this a new post? If so, we need to create
			// the basic post record before we do anything else.
			if ($this->this_revision_needs_original_post()) :
				// *sigh*, for handling inconsistent slash expectations < 3.6
				$sdbpost = $this->db_sanitize_post($dbpost);
				
				// Go ahead and insert the first post record to
				// anchor the revision history.
				$this->_wp_id = wp_insert_post($sdbpost, /*return wp_error=*/ true);

db_sanitize_post says:

	function db_sanitize_post ($out) {
		// < 3.6. Core API, including wp_insert_post(), will expect
		// properly slashed data. If wp_slash() exists, then this is
		// after the big change-over, and wp_insert_post() etc. will
		// expect *un*-slashed data.
		if (!function_exists('wp_slash')) :
		
			foreach ($out as $key => $value) :
				if (is_string($value)) :
					$out[$key] = esc_sql($value);
				else :
					$out[$key] = $value;
				endif;
			endforeach;

		endif;

That is, nothing is being done on WP 3.6+.

Meanwhile, I don't know about older versions, but modern Wordpress (4.0+) appears to expect slashed data in wp_insert_post after all!

Not only various sources confirm this, if we look into [_wp_put_post_revision code](https://developer.wordpress.org/reference/functions/_wp_put_post_revision/), it does it too:

    $post = wp_slash($post); //since data is from db
     $revision_id = wp_insert_post( $post );

So the post seems to need to be slashed. And indeed, FWP loses backslashes in syndicated posts as it is.

My suggested fix is to add this in db_sanitize_post just before the endif

		else:
			$out = wp_slash($out);

And remove the comment about 3.6+ core api requiring unslashed data (or update it to indicate which versions indeed needed it and which are now not).

**Comment by radgeek** [comment]
Thanks for tracking this down. It took some sleuthing through the change logs for the WordPress core to figure out what was going on, but it turns out the issue was that the devs made a big, across-the-board change to slashing expectations, and then reverted that change later, in kind of a weird way (  cf. https://core.trac.wordpress.org/browser/trunk/wp-includes/post.php?rev=23416 vs. https://core.trac.wordpress.org/changeset/23554/trunk/wp-includes/post.php?contextall=1 -- they didn't actually remove the code adding slashes to the database fields in `wp_insert_post` but rather added an additional function call, with the effect of stripping out slashes, passing the unslashed data around, and then re-adding the slashes later on ). In any case, I just committed a fix that does basically what you suggest, with a little more fine-grained version-checking added in that should hopefully get as close as reasonably possible to satisfying requirements across all the relevant versions. Give it a pull and let me know if it works for you.
