### ISSUE TITLE
This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line XX, column YYY

### ISSUE THREAD

**Issue by leotulipan** [radgeek/feedwordpress#57]
> discussed here https://wordpress.org/support/topic/plugin-feedwordpress-xml-errors-reported and more recently here https://wordpress.org/support/topic/rssxml-error-for-my-other-wordpress-site

I looked into this a bit more, but I had a hard time understanding the async/class structure of the code.

**The error message comes from line 1439 in wp-includes/class-simplepie.php.**

This got changed in the Wordpress source on Sep 20 with a commit https://github.com/WordPress/WordPress/commit/84da11d91826f3de1210ecdca6156ab951a53d48 that added a new argument.
I'm quite sure it's something else though... Some other small changes with dates happened in the SimplePie Directory.
# SO: how can we help further debug this?

**Comment by radgeek** [comment]
I'm sorry to close this issue without having offered more meaningful feedback. I've made some substantial changes to FeedWordPress's parsing of XML feeds in order to make it somewhat more fault tolerant (so as to make errors like these less likely), and the WordPress team has now also bundled in a major upgrade to SimplePie which should also help address other issues that might lead to this kind of error. If you run into this issue with a current version of FeedWordPress, please feel free to open an issue, with a sample URL for one or more of the feed(s) where you are seeing this error message.
