### ISSUE TITLE
Why pull requests are not merged?

### ISSUE THREAD

**Issue by tristanleboss** [radgeek/feedwordpress#62]
Hello,

I was wondering why the pull requests are not merged?

I looked at them and they all look fine.

Regards,

Tristan

**Comment by radgeek** [comment]
Hi there,

Thank you for the reminder to look through these. I have been spending some time the last couple months trying to get caught up with work on FeedWordPress support requests, issue reports and pull requests, which I hadn't been able to attend to for a while due to my new academic schedule. Hopefully I should have all of the pull requests processed one way or another within the next couple of days. Let me know if you have any questions.

Cheers,
-C

**Comment by tristanleboss** [comment]
I don't understand why this issue has been closed? I also don't understand why pull requests are not merged. I have to edit PHP files each time I update the plugin... :-1:
