### ISSUE TITLE
"No Review" problem

### ISSUE THREAD

**Issue by MetzKetz** [radgeek/feedwordpress#63]
As title say, none of my posts have a review image.
Is that a bug or just not a feature?

**Comment by radgeek** [comment]
Hi @MetzKetz,

I think I probably have an answer for you, but to make sure that I understand what you're asking, what do you mean by a "Review Image"? Are you using a specialized theme or plugin like https://wordpress.org/plugins/wp-product-review/ that provides formatting options for product reviews?

Thanks,
-C

**Comment by MetzKetz** [comment]
Yes, I'm sorry. I think it actually has nothing to do with your plugin.
This was my "problem": http://prntscr.com/bmkm0l

I thought your plugin pulls automatic a thumbnail / preview image.
But meanwhile fixed it with "Magic Post Thumbnail" :)

**Comment by radgeek** [comment]
Okay, great! Glad you found a solution to the issue.

Briefly, for anyone else looking through this thread, if you need to generate Thumbnails or Featured Images for your syndicated posts, FeedWordPress has no good way of doing that "off the shelf" (because it's actually kind of complicated, due to the way that WordPress implements Featured Images). However, if you need to generate Featured Images for your posts, you can do it either by using an independent WordPress plugin, like the one MetzKetz mentions above (<https://wordpress.org/plugins/magic-post-thumbnail/>), or else by using an add-on for FeedWordPress that allows you to capture local copies of images and make use of them for Featured Images or Thumbnails -- for example, I have a free experimental add-on that takes care of this called FWP+: SIC 'Em, here: <https://github.com/radgeek/FWP---SIC--Em>

Hope this helps!
